# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user1_id',
        ),
    ]
